### ISSUE TITLE
Outward facing documentation

### ISSUE THREAD

**Issue by disa-mhembere** [neurodata-arxiv/blci#20]
Make a website. Sphinx should do ..

**Comment by gkiar** [comment]
If you copy the docs folder of ndmg it has instructions and a setup config
file for aurodoccing which makes it super easy. You'll just need to change
which directories you're importing in config.py :)

**Comment by disa-mhembere** [comment]
Well ain't that convenient -- thanks :)



On Dec 10, 2016 8:15 AM, "Greg Kiar" <notifications@github.com> wrote:

If you copy the docs folder of ndmg it has instructions and a setup config
file for aurodoccing which makes it super easy. You'll just need to change
which directories you're importing in config.py :)

—
You are receiving this because you were assigned.
Reply to this email directly, view it on GitHub
<https://github.com/neurodata/blci/issues/20#issuecomment-266207232>, or mute
the thread

**Comment by disa-mhembere** [comment]
This exists now [https://neurodata.github.io/blci](https://neurodata.github.io/blci) for the most part, but there are 3 important and larger files that I've decomposed into tasks. The new tasks are [1](https://github.com/neurodata/blci/issues/24), [2](https://github.com/neurodata/blci/issues/25), [3](https://github.com/neurodata/blci/issues/26).
