### ISSUE TITLE
send greg link to test

### ISSUE THREAD

**Issue by gkiar** [neurodata-arxiv/blci#21]

**Comment by disa-mhembere** [comment]
After the holidays: [https://neurodata.github.io/blci/tutorial.html](https://neurodata.github.io/blci/tutorial.html)

**Comment by disa-mhembere** [comment]
@gkiar Please make issues if you have problems `init`ing and `add`ing a blci repo. Note the `add` adds, commits, creates a remote, pushes, Travis tracks and builds ..
